#ifndef UNINASOC_H
#define UNINASOC_H

#include "stdlib.h"

// This header is autogenerated based on project configuration
#include "uninasoc_conf.h"

#include "irq_handlers.h"
#include "plic.h"

#ifdef GPIOIN_IS_ENABLED
#include "xlnx_gpio_in.h"
#endif

#ifdef GPIOOUT_IS_ENABLED
#include "xlnx_gpio_out.h"
#endif

#ifdef TIM_IS_ENABLED
#include "xlnx_tim.h"
#endif

#ifdef CDMA_IS_ENABLED
#include "xlnx_cdma.h"
#endif

#ifdef UART_IS_ENABLED
#include "tinyIO.h"
#endif

enum{
    UNINASOC_OK,
    UNINASOC_ERROR
};

static inline void uninasoc_init()
{
    // TinyIO init
    uintptr_t uart_base_address = (uintptr_t)_peripheral_UART_start;
    tinyIO_init(uart_base_address);
}

#endif
